config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :users, except: [:new]
  resources :articles
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 5000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end

  def setup_navbar
    @users = User.all
    @categories = Category.all
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :setup_navbar, only: [:index, :show]

  def new
    @article = Article.new
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order("created_at DESC")
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to articles_path
    else
      render plain: @article.errors.full_messages
    end
  end

  def edit
  end

  def show
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render plain: @article.errors.full_messages
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        render plain: "wait... that's illegal"
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :new, :create]
  before_action :require_admin, except: [:index, :show]
  before_action :setup_navbar, only: [:index, :show]

  def new
    @category = Category.new
  end

  def index
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render plain: @category.errors.full_messages
    end
  end

  def edit
  end

  def show
    @articles = @category.articles
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render plain: @category.errors.full_messages
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end
  
    def require_admin
      if !(logged_in? && current_user.admin?)
        render plain: "[categories] wait... that's illegal. Only admin can do that."
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    redirect_to articles_path if logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email_or_username].downcase)
    if !user
      user = User.find_by(username: params[:session][:email_or_username].downcase)
    end

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      session[:username] = user.username
      redirect_to root_path
    else
      render plain: "incorrect info"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :setup_navbar, only: [:index, :show]

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      user = User.find_by(email: user_params["email"].downcase)
      session[:user_id] = user.id
      session[:username] = user.username
      redirect_to root_path
    else
      render plain: @user.errors.full_messages
    end
  end

  def edit
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5).order("created_at DESC")
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render plain: @user.errors.full_messages
    end
  end

  def destroy
    @user.destroy
    if current_user == @user
      session.destroy
    end
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:username, :description, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        render plain: "wait... that's illegal"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.reverse_each do |article| %>
    <div class="card">
      <div class="card-body">
        <h4><%= link_to article.title, article_path(article), class: "card-title" %></h4>
        <h6 class="card-subtitle mb-2 text-muted">@<%= link_to article.user.username, user_path(article.user), class: "text-muted", style: "text-decoration: none; font-weight: bold" %> · <%= time_ago_in_words(article.updated_at) %> ago</h6>
        <p><pre><%= article.description %></pre></p>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_article_list.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="card">
      <div class="card-body">
        <%= render article.categories %>
        <h4><%= link_to article.title, article_path(article), class: "card-title" %></h4>
        <h6 class="card-subtitle mb-2 text-muted">@<%= link_to article.user.username, user_path(article.user), class: "text-muted", style: "text-decoration: none; font-weight: bold" %> · <%= time_ago_in_words(article.updated_at) %> ago</h6>
        <hr>
        <p><pre><%= article.description %></pre></p>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container mt-3">
  <%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title, class: "h5 form-label" %><br>
      <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1" %>
    </div>
  
    <div>
      <%= form.label :description, class: "h5 form-label" %><br>
      <%= form.text_area :description, class: "form-control mh-100", id: "exampleFormControlTextarea1", rows: "20" %>
    </div>

    <div>
      <%= form.label :category, class: "h5 form-label" %><br>
      <%= form.collection_select(:category_ids, Category.all, :id, :name,
            { include_blank: 'None' }, { multiple: true, class: "form-control mh-100" }) %>
    </div>
  
    <div class="mt-5">
      <div class="btn-group" role="group" aria-label="Basic mixed styles example">
        <%= link_to "Return", articles_path, class: "btn btn-outline-warning" %>
        <%= form.submit class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_small_form.html.erb
<div class="container mt-3">
  <%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title, class: "h5 form-label" %><br>
      <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1" %>
    </div>
  
    <div>
      <%= form.label :description, class: "h5 form-label" %><br>
      <%= form.text_area :description, class: "form-control mh-100", id: "exampleFormControlTextarea1" %>
    </div>

    <div>
      <%= form.label :category, class: "h5 form-label" %><br>
      <%= form.collection_select(:category_ids, Category.all, :id, :name,
            { include_blank: 'None' }, { multiple: true, class: "form-control mh-100" }) %>
    </div>
  
    <div class="d-flex justify-content-end bd-highlight mt-3 mb-4">
      <%= form.submit class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
      
    </div>
  <% end %>
</div>

app/views/articles/_smallform.html.erb
<div class="container mt-3">
  <%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title, class: "h5 form-label" %><br>
      <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1" %>
    </div>
  
    <div>
      <%= form.label :description, class: "h5 form-label" %><br>
      <%= form.text_area :description, class: "form-control mh-100", id: "exampleFormControlTextarea1" %>
    </div>
  
    <div class="mt-3 mb-4">
      <%= form.submit class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
      
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">

    </div>
    <div class="col-7">
      <%= render "shared/return_nav", obj: @article, txt: "Edit" %>
    
      <%= render 'form' %>
    </div>
    <div class="col">

    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>

    <div class="col-7">
      <div class="container border sticky-top bg-light pt-2 pb-2">
        <h2>Latest Articles</h2>
      </div>
      <div class="border pb-3">
        <%= render 'small_form' %>
        <%= render 'article_list' %>
        <div class="d-flex justify-content-center bd-highlight mt-3">
          <ul class="pagination">
            <li><%= will_paginate @articles, class: "page-link" %></li>
          </ul>
        </div>
      </div>
    </div>
    
    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <%= render "shared/return_nav", obj: articles_path, txt: "Create" %>
  <h1 class="mt-4">What the hell is going on</h1>

  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>

    <div class="col-7">
      <%= render "shared/return_nav", obj: articles_path, txt: "Article" %>
      <div class="card container mt-4">
        <div class="card-body">
          <%= render @article.categories %>
          <h4><%= @article.title %></h4>
          <h6 class="card-subtitle mb-2 text-muted">@<%= link_to @article.user.username, user_path(@article.user), class: "text-muted", style: "text-decoration: none; font-weight: bold" %> · <%= time_ago_in_words(@article.updated_at) %> ago</h6>
          <hr>
          <p><pre><%= @article.description %></pre></p>
        </div>
      </div>
      <div class="container mt-5 mb-5">
        <div class="btn-group d-flex justify-content-center"" role="group" aria-label="Basic mixed styles example">
          <%= link_to "Return", articles_path, class: "btn btn-primary" %>
          <% if logged_in? && (@article.user == current_user || current_user.admin? )%>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "h6 btn btn-success me-1 pt-1" %>

app/views/categories/_category_list.html.erb
<% @categories.each do |category| %>
  <%= link_to category_path(category), style: "text-decoration: none;", :action => 'go' do %>
    <div class="card">
      <div class="card-body">
        <h1><%= category.name %> [<%= category.articles.count %>]</h1>
      </div>
    </div>
  <% end %>
<% end %>

app/views/categories/_category_list_small.html.erb
<h2>Topics</h2>
<% @categories.limit(4).each do |category| %>
  <%= link_to category_path(category), style: "text-decoration: none;", :action => 'go' do %>
    <div class="card">
      <div class="card-body">
        <h6><%= category.name %></h6>
      </div>
    </div>
  <% end %>
<% end %>
<h5 class="mt-2"><%= link_to "See more", categories_path, style: "text-decoration: none" %></h5>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name, "Category name", class: "h5 form-label" %><br>
    <%= form.text_field :name, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div class="mt-4">
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= form.submit class: "btn btn-primary", data: { confirm: "Are you sure?" } %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <%= render "shared/return_nav", obj: @category, txt: "Edit" %>
  <h1 class="mt-4">Edit</h1>

  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>
    
    <div class="col-7">
      <%= render "shared/return_nav", obj: articles_path, txt: "Categories" %>
      <div class="container border pt-4 pb-4">
        <%= render 'category_list' %>
      </div>
    </div>

    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      
    </div>
    <div class="col-7">
      <%= render "shared/return_nav", obj: root_path %>
      <div class="container mt-5">
        <h1>Create new category</h1>
        <%= render 'form' %>
      </div>

    </div>
    <div class="col">
      
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>

    <div class="col-7">
      <%= render "shared/return_nav", obj: articles_path, txt: @category.name %>
      <div class="container border p-0 pt-4 pb-4">
        <%= render 'articles/article_list' %>
      </div>
    </div>

    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a><%= link_to "ALPHA", root_path, class: "navbar-brand" %></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a><%= link_to "Home", root_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <a><%= link_to "Articles", articles_path, class: "nav-link" %></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>DA HOME PAGE</h1>
  <%= link_to "Sign up", signup_path %>
  <%= link_to "Log in", login_path %>
</body>
</html>

app/views/shared/_main_nav.html.erb
<div class="sticky-top overflow-auto vh-100">
  <h2>ALPHA BLOG</h2>
  <ul class="list-group mt-3">
    <%= link_to "Home", articles_path, class: "list-group-item #{"active" if current_page?(articles_path)}" %>
    <%= link_to "Users", users_path, class: "list-group-item #{"active" if current_page?(users_path)}" %>
    <%= link_to "Categories", categories_path, class: "list-group-item #{"active" if current_page?(categories_path)}" %>
    <%= link_to "Profile", current_user, class: "list-group-item #{"active" if current_page?(current_user)}" %>
  </ul>
  <div class="container position-absolute bottom-0 start-0 mb-4">
    <div class="btn-group dropup">
      <button type="button" class="btn dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.username %>
      </button>
      <ul class="dropdown-menu">
        <%= link_to "Profile", current_user, class: "list-group-item #{"active" if current_page?(current_user)}" %>
        <%= link_to "Log out", logout_path, class: "list-group-item btn-outline-danger", data: { confirm: "Are you sure you want to log out?" }, method: :delete %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_return_nav.html.erb
<div class="sticky-top bg-light">
  <div class="fs-2 container border pt-2 pb-2">
    <%= link_to obj, style: "text-decoration: none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"></path>
      </svg>
    <% end %>
    <span><%= defined?(txt) ? txt : "Return" %></span>
  </div>
</div>

app/views/shared/_side_nav.html.erb
<div class="sticky-top">
  <div class="container border mt-5 mb-5 pt-2 pb-2">
    <%= render 'users/user_list_small' %>
  </div>
  <div class="container border mt-5 mb-5 pt-2 pb-2">
    <%= render 'categories/category_list_small' %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username, class: "h5 form-label" %><br>
    <%= form.text_field :username, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div>
    <%= form.label :description, class: "h5 form-label" %><br>
    <%= form.text_area :description, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div>
    <%= form.label :email, class: "h5 form-label" %><br>
    <%= form.email_field :email, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div>
    <%= form.label :password, class: "h5 form-label" %><br>
    <%= form.password_field :password, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div>
    <%= form.label :password_confirmation, "Repeat password", class: "h5 form-label" %><br>
    <%= form.password_field :password_confirmation, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div class="mt-4">
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary", data: { confirm: "Are you sure?" }) %>
    </div>
  </div>
<% end %>

app/views/users/_user_list.html.erb
<% @users.each do |user| %>
  <%= link_to user_path(user), style: "text-decoration: none;", :action => 'go' do %>
    <div class="card">
      <div class="card-body">
        <h1><%= user.username %></h1>
        <span class="text-muted"><%= user.email%></span>
        <br>
        <span class="text-dark"><%= user.description %></span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_user_list_small.erb
<h2>Users</h2>
<% @users.limit(4).each do |user| %>
  <%= link_to user_path(user), style: "text-decoration: none;", :action => 'go' do %>
    <div class="card">
      <div class="card-body">
        <h6><%= user.username %></h6>
        <span class="text-muted"><%= user.email%></span>
        <br>
      </div>
    </div>
  <% end %>
<% end %>
<h5 class="mt-2"><%= link_to "See more", users_path, style: "text-decoration: none" %></h5>

app/views/users/edit.html.erb
<div class="container">
  <%= render "shared/return_nav", obj: @user, txt: "Edit" %>
  <h1 class="mt-4">Edit</h1>

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>
    <div class="col-7">
      <%= render "shared/return_nav", obj: articles_path, txt: "Check out these users" %>
      <div class="container border pt-4 pb-4">
        <%= render 'user_list' %>
      </div>
      <div class="d-flex justify-content-center bd-highlight mt-3">
        <ul class="pagination">
          <li><%= will_paginate @users, class: "page-link" %></li>
        </ul>
      </div>
    </div>
    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
      
    </div>
    <div class="col-7">
      <%= render "shared/return_nav", obj: root_path %>
      <div class="container mt-5">
        <h1>Create your account</h1>
        <%= render 'form' %>
      </div>

    </div>
    <div class="col">
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-2">
      <%= render 'shared/main_nav' %>
    </div>

    <div class="col-7">
      <%= render "shared/return_nav", obj: articles_path, txt: pluralize(@user.articles.count, "article") %>
      <div class="container border p-0">
        <div class="container d-flex bd-highlight mt-4 mb-2">
          <div class="p-2 w-100 bd-highlight">
            <h1><%= @user.username %><%= " 👷" if @user.admin? %></h1>
            <span class="text-muted"><%= @user.email %></span>
            <br><br>
            <span><%= @user.description %></span>
          </div>
          <% if @user == current_user %>
            <div class="p-2 flex-shrink-1 bd-highlight">
              <div class="dropstart">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <%= link_to "Edit", edit_user_path(@user), class: "list-group-item" %>
                  <%= link_to "Delete account", user_path(@user), class: "list-group-item btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
        <%= render 'articles/article_list' %>
        <div class="d-flex justify-content-center bd-highlight mt-3">
          <ul class="pagination">
            <li><%= will_paginate @articles, class: "page-link" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col">
      <%= render 'shared/side_nav' %>
    </div>
  </div>
</div>